### ISSUE TITLE
Program Crashed!

### ISSUE THREAD

**Issue by edgar1016** [micah686/VnManager#21]
Building and running on Visual Studio worked just fine up until I installed release 1.0.1. After installing it I got this error when running both the release and the build now. When I get this error nothing is logged the only way to get the stack trace was through visual studio.

Edit: I was able to reproduce this issue in a windows sand box. On initial install of 1.0.1 when clicking yes in the "Update Available" box it continues to "Set a password" I select **No** then **Submit** after submitting it sometimes crashes then it no longer allows me to open the app and I get the error mentioned. I noticed as well that on every launch after a successful install the "Update Available" screen pops up every time you boot the app up when clicking yes it does nothing app stays on v1.0.0.

`System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=LiteDB
  StackTrace:
   at LiteDB.DictionaryExtensions.<ParseKeyValue>g__ReadValue|2_1(<>c__DisplayClass2_0& )
   at LiteDB.DictionaryExtensions.ParseKeyValue(IDictionary`2 dict, String connectionString)
   at LiteDB.ConnectionString..ctor(String connectionString)
   at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)
   at VnManager.Initializers.PreStartupCheck.SetupCategories() in C:\Users\edgar\source\repos\VnManager\src\VnManager\Initializers\PreStartupCheck.cs:line 169
   at VnManager.Initializers.PreStartupCheck.StartupPrep() in C:\Users\edgar\source\repos\VnManager\src\VnManager\Initializers\PreStartupCheck.cs:line 32
   at VnManager.Bootstrapper.OnStart() in C:\Users\edgar\source\repos\VnManager\src\VnManager\Bootstrapper.cs:line 28
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at VnManager.App.Main()

  This exception was originally thrown at this call stack:
    LiteDB.DictionaryExtensions.ParseKeyValue.__ReadValue|2_1(ref LiteDB.DictionaryExtensions.<>c__DisplayClass2_0)
    LiteDB.DictionaryExtensions.ParseKeyValue(System.Collections.Generic.IDictionary<string, string>, string)
    LiteDB.ConnectionString.ConnectionString(string)
    LiteDB.LiteDatabase.LiteDatabase(string, LiteDB.BsonMapper)
    VnManager.Initializers.PreStartupCheck.SetupCategories() in PreStartupCheck.cs
    VnManager.Initializers.PreStartupCheck.StartupPrep() in PreStartupCheck.cs
    VnManager.Bootstrapper.OnStart() in Bootstrapper.cs
    Stylet.BootstrapperBase.Start(string[])
    Stylet.BootstrapperBase.Setup.AnonymousMethod__9_0(object, System.Windows.StartupEventArgs)
    System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
    ...
    [Call Stack Truncated]`

**Comment by edgar1016** [comment]
After a few hours, i've narrowed down what's causing the issue. Deleting the credentials restarts the setup process again, this seems to of have fixed the issue. The software doesn't seem to play nice with certain credentials it generates, It's like a 50% chance that the initial credential generated will be accepted. The credential causing this problem is VnManager.DbEnc when testing sometimes I'd have to generate up to 4 different credentials before it stuck.

**Comment by micah686** [comment]
For the update available, it was because I accidentally tagged the release as 1.0.**1**, instead of 1.0.0. I just deleted the old tag and tagged it with the correct 1.0.0, so it should work now.

As for the credential issue, I'll look into it, and see what's going on.

**Comment by micah686** [comment]
@edgar1016 , Could you try this release that I attached? I should have fixed it on this commit: https://github.com/micah686/VnManager/tree/1137a1bc0bcc2e4f51557c404829df7d53579d63  


[VnManager-Setup.zip](https://github.com/micah686/VnManager/files/6056354/VnManager-Setup.zip)  
If there are any issues, please let me know

**Comment by edgar1016** [comment]
Tested it. Issue persist it's still about 50/50 on whether or not it I get the error. Were you able to reproduce the issue on your end?

**Comment by micah686** [comment]
Hmmm..... 
I'll look into it a bit more. I was partially able to replicate it on my end. It seems like it's not triggering as much when I'm debugging vs running the program from the executable itself, which is making finding the problematic section/variables somewhat difficult.
I'll keep working on it, and see what I can do.

**Comment by micah686** [comment]
Ok, I think I found the issue. First, I was looking at the wrong section previously.
Second, it turns out I wasn't encapsulating the passwords correctly. So when it encountered certain special characters like = or ;,  it broke connection to the database. The most recent build should have this fixed.

**Comment by edgar1016** [comment]
Yup that seems to of done it, thanks! I'm glad this one was quashed quickly, also really happy to see this project comeback to life. I've been following the project since the original v1 years ago. I've started learning C# in hope that I can contribute to this project in a meaningful way in the future. Thanks for your hard work!

**Comment by micah686** [comment]
@edgar1016 , Please redownload the latest release. I forgot to change the version number in the program, So if you don't get the latest one, it will always think there is a newer version.
